//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError, AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export interface ISocialCoordinationApiClient {
    /**
     * @param body (optional) 
     * @return Created
     */
    groupsPOST(body: CreateGroupRequest | undefined): Promise<GroupResponse>;
    /**
     * @return Success
     */
    groupsAll(): Promise<GroupSummaryResponse[]>;
    /**
     * @return Success
     */
    groupsGET(id: string): Promise<GroupResponse>;
    /**
     * @param body (optional) 
     * @return Success
     */
    groupsPUT(id: string, body: UpdateGroupRequest | undefined): Promise<GroupResponse>;
    /**
     * @return No Content
     */
    groupsDELETE(id: string): Promise<void>;
    /**
     * @param body (optional) 
     * @return Success
     */
    membersPOST(id: string, body: AddGroupMemberRequest | undefined): Promise<GroupResponse>;
    /**
     * @return Success
     */
    membersDELETE(id: string, memberUserId: string): Promise<GroupResponse>;
    /**
     * @param body (optional) 
     * @return Created
     */
    hangoutsPOST(body: CreateHangoutRequest | undefined): Promise<HangoutResponse>;
    /**
     * @return Success
     */
    hangoutsAll(): Promise<HangoutSummaryResponse[]>;
    /**
     * @return Success
     */
    hangoutsGET(id: string): Promise<HangoutResponse>;
    /**
     * @param body (optional) 
     * @return Success
     */
    hangoutsPUT(id: string, body: UpdateHangoutRequest | undefined): Promise<HangoutResponse>;
    /**
     * @return No Content
     */
    hangoutsDELETE(id: string): Promise<void>;
    /**
     * @param body (optional) 
     * @return Success
     */
    rsvp(id: string, body: UpdateRSVPRequest | undefined): Promise<HangoutResponse>;
    /**
     * @return Success
     */
    cancel(id: string): Promise<HangoutResponse>;
    /**
     * @return Success
     */
    health(): Promise<void>;
    /**
     * @return Success
     */
    seed(): Promise<void>;
    /**
     * @param body (optional) 
     * @return Success
     */
    mePOST(body: CreateUserRequest | undefined): Promise<UserResponse>;
    /**
     * @return Success
     */
    meGET(): Promise<UserResponse>;
    /**
     * @param body (optional) 
     * @return Success
     */
    mePUT(body: UpdateUserRequest | undefined): Promise<UserResponse>;
    /**
     * @return No Content
     */
    meDELETE(): Promise<void>;
    /**
     * @param q (optional) 
     * @return Success
     */
    search(q: string | undefined): Promise<UserResponse[]>;
}

export class SocialCoordinationApiClient implements ISocialCoordinationApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * @param body (optional) 
     * @return Created
     */
    groupsPOST(body: CreateGroupRequest | undefined, cancelToken?: CancelToken): Promise<GroupResponse> {
        let url_ = this.baseUrl + "/api/groups";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGroupsPOST(_response);
        });
    }

    protected processGroupsPOST(response: AxiosResponse): Promise<GroupResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 201) {
            const _responseText = response.data;
            let result201: any = null;
            let resultData201  = _responseText;
            result201 = GroupResponse.fromJS(resultData201);
            return Promise.resolve<GroupResponse>(result201);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GroupResponse>(null as any);
    }

    /**
     * @return Success
     */
    groupsAll( cancelToken?: CancelToken): Promise<GroupSummaryResponse[]> {
        let url_ = this.baseUrl + "/api/groups";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGroupsAll(_response);
        });
    }

    protected processGroupsAll(response: AxiosResponse): Promise<GroupSummaryResponse[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(GroupSummaryResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<GroupSummaryResponse[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GroupSummaryResponse[]>(null as any);
    }

    /**
     * @return Success
     */
    groupsGET(id: string, cancelToken?: CancelToken): Promise<GroupResponse> {
        let url_ = this.baseUrl + "/api/groups/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGroupsGET(_response);
        });
    }

    protected processGroupsGET(response: AxiosResponse): Promise<GroupResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = GroupResponse.fromJS(resultData200);
            return Promise.resolve<GroupResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GroupResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    groupsPUT(id: string, body: UpdateGroupRequest | undefined, cancelToken?: CancelToken): Promise<GroupResponse> {
        let url_ = this.baseUrl + "/api/groups/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGroupsPUT(_response);
        });
    }

    protected processGroupsPUT(response: AxiosResponse): Promise<GroupResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = GroupResponse.fromJS(resultData200);
            return Promise.resolve<GroupResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GroupResponse>(null as any);
    }

    /**
     * @return No Content
     */
    groupsDELETE(id: string, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/groups/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGroupsDELETE(_response);
        });
    }

    protected processGroupsDELETE(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    membersPOST(id: string, body: AddGroupMemberRequest | undefined, cancelToken?: CancelToken): Promise<GroupResponse> {
        let url_ = this.baseUrl + "/api/groups/{id}/members";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMembersPOST(_response);
        });
    }

    protected processMembersPOST(response: AxiosResponse): Promise<GroupResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = GroupResponse.fromJS(resultData200);
            return Promise.resolve<GroupResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GroupResponse>(null as any);
    }

    /**
     * @return Success
     */
    membersDELETE(id: string, memberUserId: string, cancelToken?: CancelToken): Promise<GroupResponse> {
        let url_ = this.baseUrl + "/api/groups/{id}/members/{memberUserId}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (memberUserId === undefined || memberUserId === null)
            throw new Error("The parameter 'memberUserId' must be defined.");
        url_ = url_.replace("{memberUserId}", encodeURIComponent("" + memberUserId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMembersDELETE(_response);
        });
    }

    protected processMembersDELETE(response: AxiosResponse): Promise<GroupResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = GroupResponse.fromJS(resultData200);
            return Promise.resolve<GroupResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GroupResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Created
     */
    hangoutsPOST(body: CreateHangoutRequest | undefined, cancelToken?: CancelToken): Promise<HangoutResponse> {
        let url_ = this.baseUrl + "/api/hangouts";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processHangoutsPOST(_response);
        });
    }

    protected processHangoutsPOST(response: AxiosResponse): Promise<HangoutResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 201) {
            const _responseText = response.data;
            let result201: any = null;
            let resultData201  = _responseText;
            result201 = HangoutResponse.fromJS(resultData201);
            return Promise.resolve<HangoutResponse>(result201);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<HangoutResponse>(null as any);
    }

    /**
     * @return Success
     */
    hangoutsAll( cancelToken?: CancelToken): Promise<HangoutSummaryResponse[]> {
        let url_ = this.baseUrl + "/api/hangouts";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processHangoutsAll(_response);
        });
    }

    protected processHangoutsAll(response: AxiosResponse): Promise<HangoutSummaryResponse[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(HangoutSummaryResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<HangoutSummaryResponse[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<HangoutSummaryResponse[]>(null as any);
    }

    /**
     * @return Success
     */
    hangoutsGET(id: string, cancelToken?: CancelToken): Promise<HangoutResponse> {
        let url_ = this.baseUrl + "/api/hangouts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processHangoutsGET(_response);
        });
    }

    protected processHangoutsGET(response: AxiosResponse): Promise<HangoutResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = HangoutResponse.fromJS(resultData200);
            return Promise.resolve<HangoutResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<HangoutResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    hangoutsPUT(id: string, body: UpdateHangoutRequest | undefined, cancelToken?: CancelToken): Promise<HangoutResponse> {
        let url_ = this.baseUrl + "/api/hangouts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processHangoutsPUT(_response);
        });
    }

    protected processHangoutsPUT(response: AxiosResponse): Promise<HangoutResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = HangoutResponse.fromJS(resultData200);
            return Promise.resolve<HangoutResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<HangoutResponse>(null as any);
    }

    /**
     * @return No Content
     */
    hangoutsDELETE(id: string, cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/hangouts/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processHangoutsDELETE(_response);
        });
    }

    protected processHangoutsDELETE(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    rsvp(id: string, body: UpdateRSVPRequest | undefined, cancelToken?: CancelToken): Promise<HangoutResponse> {
        let url_ = this.baseUrl + "/api/hangouts/{id}/rsvp";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRsvp(_response);
        });
    }

    protected processRsvp(response: AxiosResponse): Promise<HangoutResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = HangoutResponse.fromJS(resultData200);
            return Promise.resolve<HangoutResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<HangoutResponse>(null as any);
    }

    /**
     * @return Success
     */
    cancel(id: string, cancelToken?: CancelToken): Promise<HangoutResponse> {
        let url_ = this.baseUrl + "/api/hangouts/{id}/cancel";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCancel(_response);
        });
    }

    protected processCancel(response: AxiosResponse): Promise<HangoutResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = HangoutResponse.fromJS(resultData200);
            return Promise.resolve<HangoutResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<HangoutResponse>(null as any);
    }

    /**
     * @return Success
     */
    health( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/health";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processHealth(_response);
        });
    }

    protected processHealth(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return Success
     */
    seed( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/Seed";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "POST",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processSeed(_response);
        });
    }

    protected processSeed(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    mePOST(body: CreateUserRequest | undefined, cancelToken?: CancelToken): Promise<UserResponse> {
        let url_ = this.baseUrl + "/api/users/me";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMePOST(_response);
        });
    }

    protected processMePOST(response: AxiosResponse): Promise<UserResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = UserResponse.fromJS(resultData200);
            return Promise.resolve<UserResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<UserResponse>(null as any);
    }

    /**
     * @return Success
     */
    meGET( cancelToken?: CancelToken): Promise<UserResponse> {
        let url_ = this.baseUrl + "/api/users/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMeGET(_response);
        });
    }

    protected processMeGET(response: AxiosResponse): Promise<UserResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = UserResponse.fromJS(resultData200);
            return Promise.resolve<UserResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<UserResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    mePUT(body: UpdateUserRequest | undefined, cancelToken?: CancelToken): Promise<UserResponse> {
        let url_ = this.baseUrl + "/api/users/me";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMePUT(_response);
        });
    }

    protected processMePUT(response: AxiosResponse): Promise<UserResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = UserResponse.fromJS(resultData200);
            return Promise.resolve<UserResponse>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<UserResponse>(null as any);
    }

    /**
     * @return No Content
     */
    meDELETE( cancelToken?: CancelToken): Promise<void> {
        let url_ = this.baseUrl + "/api/users/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processMeDELETE(_response);
        });
    }

    protected processMeDELETE(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param q (optional) 
     * @return Success
     */
    search(q: string | undefined, cancelToken?: CancelToken): Promise<UserResponse[]> {
        let url_ = this.baseUrl + "/api/users/search?";
        if (q === null)
            throw new Error("The parameter 'q' cannot be null.");
        else if (q !== undefined)
            url_ += "q=" + encodeURIComponent("" + q) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "text/plain"
            },
            cancelToken
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processSearch(_response);
        });
    }

    protected processSearch(response: AxiosResponse): Promise<UserResponse[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(UserResponse.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return Promise.resolve<UserResponse[]>(result200);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<UserResponse[]>(null as any);
    }
}

export class AddGroupMemberRequest implements IAddGroupMemberRequest {
    userId?: string | undefined;

    constructor(data?: IAddGroupMemberRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
        }
    }

    static fromJS(data: any): AddGroupMemberRequest {
        data = typeof data === 'object' ? data : {};
        let result = new AddGroupMemberRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        return data;
    }
}

export interface IAddGroupMemberRequest {
    userId?: string | undefined;
}

export class CreateGroupRequest implements ICreateGroupRequest {
    name?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    memberUserIds?: string[] | undefined;

    constructor(data?: ICreateGroupRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.emoji = _data["emoji"];
            this.description = _data["description"];
            if (Array.isArray(_data["memberUserIds"])) {
                this.memberUserIds = [] as any;
                for (let item of _data["memberUserIds"])
                    this.memberUserIds!.push(item);
            }
        }
    }

    static fromJS(data: any): CreateGroupRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateGroupRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["emoji"] = this.emoji;
        data["description"] = this.description;
        if (Array.isArray(this.memberUserIds)) {
            data["memberUserIds"] = [];
            for (let item of this.memberUserIds)
                data["memberUserIds"].push(item);
        }
        return data;
    }
}

export interface ICreateGroupRequest {
    name?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    memberUserIds?: string[] | undefined;
}

export class CreateHangoutRequest implements ICreateHangoutRequest {
    title?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    startTime?: Date;
    endTime?: Date | undefined;
    groupId?: string | undefined;
    inviteeUserIds?: string[] | undefined;

    constructor(data?: ICreateHangoutRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.emoji = _data["emoji"];
            this.description = _data["description"];
            this.location = _data["location"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.groupId = _data["groupId"];
            if (Array.isArray(_data["inviteeUserIds"])) {
                this.inviteeUserIds = [] as any;
                for (let item of _data["inviteeUserIds"])
                    this.inviteeUserIds!.push(item);
            }
        }
    }

    static fromJS(data: any): CreateHangoutRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateHangoutRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["emoji"] = this.emoji;
        data["description"] = this.description;
        data["location"] = this.location;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["groupId"] = this.groupId;
        if (Array.isArray(this.inviteeUserIds)) {
            data["inviteeUserIds"] = [];
            for (let item of this.inviteeUserIds)
                data["inviteeUserIds"].push(item);
        }
        return data;
    }
}

export interface ICreateHangoutRequest {
    title?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    startTime?: Date;
    endTime?: Date | undefined;
    groupId?: string | undefined;
    inviteeUserIds?: string[] | undefined;
}

export class CreateUserRequest implements ICreateUserRequest {
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    profileImageUrl?: string | undefined;

    constructor(data?: ICreateUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.email = _data["email"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.profileImageUrl = _data["profileImageUrl"];
        }
    }

    static fromJS(data: any): CreateUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["email"] = this.email;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["profileImageUrl"] = this.profileImageUrl;
        return data;
    }
}

export interface ICreateUserRequest {
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    profileImageUrl?: string | undefined;
}

export class GroupMemberResponse implements IGroupMemberResponse {
    userId?: string | undefined;
    role?: GroupMemberRole;
    joinedAt?: Date;

    constructor(data?: IGroupMemberResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.role = _data["role"];
            this.joinedAt = _data["joinedAt"] ? new Date(_data["joinedAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): GroupMemberResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GroupMemberResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["role"] = this.role;
        data["joinedAt"] = this.joinedAt ? this.joinedAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IGroupMemberResponse {
    userId?: string | undefined;
    role?: GroupMemberRole;
    joinedAt?: Date;
}

export enum GroupMemberRole {
    Admin = "Admin",
    Member = "Member",
}

export class GroupResponse implements IGroupResponse {
    id?: string | undefined;
    name?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    createdByUserId?: string | undefined;
    members?: GroupMemberResponse[] | undefined;
    createdAt?: Date;

    constructor(data?: IGroupResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.emoji = _data["emoji"];
            this.description = _data["description"];
            this.createdByUserId = _data["createdByUserId"];
            if (Array.isArray(_data["members"])) {
                this.members = [] as any;
                for (let item of _data["members"])
                    this.members!.push(GroupMemberResponse.fromJS(item));
            }
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): GroupResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GroupResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["emoji"] = this.emoji;
        data["description"] = this.description;
        data["createdByUserId"] = this.createdByUserId;
        if (Array.isArray(this.members)) {
            data["members"] = [];
            for (let item of this.members)
                data["members"].push(item.toJSON());
        }
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IGroupResponse {
    id?: string | undefined;
    name?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    createdByUserId?: string | undefined;
    members?: GroupMemberResponse[] | undefined;
    createdAt?: Date;
}

export class GroupSummaryResponse implements IGroupSummaryResponse {
    id?: string | undefined;
    name?: string | undefined;
    emoji?: string | undefined;
    memberCount?: number;

    constructor(data?: IGroupSummaryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.emoji = _data["emoji"];
            this.memberCount = _data["memberCount"];
        }
    }

    static fromJS(data: any): GroupSummaryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new GroupSummaryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["emoji"] = this.emoji;
        data["memberCount"] = this.memberCount;
        return data;
    }
}

export interface IGroupSummaryResponse {
    id?: string | undefined;
    name?: string | undefined;
    emoji?: string | undefined;
    memberCount?: number;
}

export class HangoutAttendeeResponse implements IHangoutAttendeeResponse {
    userId?: string | undefined;
    displayName?: string | undefined;
    profileImageUrl?: string | undefined;
    rsvpStatus?: RSVPStatus;
    respondedAt?: Date | undefined;

    constructor(data?: IHangoutAttendeeResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.userId = _data["userId"];
            this.displayName = _data["displayName"];
            this.profileImageUrl = _data["profileImageUrl"];
            this.rsvpStatus = _data["rsvpStatus"];
            this.respondedAt = _data["respondedAt"] ? new Date(_data["respondedAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): HangoutAttendeeResponse {
        data = typeof data === 'object' ? data : {};
        let result = new HangoutAttendeeResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["userId"] = this.userId;
        data["displayName"] = this.displayName;
        data["profileImageUrl"] = this.profileImageUrl;
        data["rsvpStatus"] = this.rsvpStatus;
        data["respondedAt"] = this.respondedAt ? this.respondedAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IHangoutAttendeeResponse {
    userId?: string | undefined;
    displayName?: string | undefined;
    profileImageUrl?: string | undefined;
    rsvpStatus?: RSVPStatus;
    respondedAt?: Date | undefined;
}

export class HangoutResponse implements IHangoutResponse {
    id?: string | undefined;
    title?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    startTime?: Date;
    endTime?: Date | undefined;
    createdByUserId?: string | undefined;
    createdByUserName?: string | undefined;
    groupId?: string | undefined;
    attendees?: HangoutAttendeeResponse[] | undefined;
    status?: HangoutStatus;
    createdAt?: Date;

    constructor(data?: IHangoutResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.emoji = _data["emoji"];
            this.description = _data["description"];
            this.location = _data["location"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.createdByUserId = _data["createdByUserId"];
            this.createdByUserName = _data["createdByUserName"];
            this.groupId = _data["groupId"];
            if (Array.isArray(_data["attendees"])) {
                this.attendees = [] as any;
                for (let item of _data["attendees"])
                    this.attendees!.push(HangoutAttendeeResponse.fromJS(item));
            }
            this.status = _data["status"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): HangoutResponse {
        data = typeof data === 'object' ? data : {};
        let result = new HangoutResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["emoji"] = this.emoji;
        data["description"] = this.description;
        data["location"] = this.location;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["createdByUserId"] = this.createdByUserId;
        data["createdByUserName"] = this.createdByUserName;
        data["groupId"] = this.groupId;
        if (Array.isArray(this.attendees)) {
            data["attendees"] = [];
            for (let item of this.attendees)
                data["attendees"].push(item.toJSON());
        }
        data["status"] = this.status;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IHangoutResponse {
    id?: string | undefined;
    title?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    startTime?: Date;
    endTime?: Date | undefined;
    createdByUserId?: string | undefined;
    createdByUserName?: string | undefined;
    groupId?: string | undefined;
    attendees?: HangoutAttendeeResponse[] | undefined;
    status?: HangoutStatus;
    createdAt?: Date;
}

export enum HangoutStatus {
    Active = "Active",
    Cancelled = "Cancelled",
    Completed = "Completed",
}

export class HangoutSummaryResponse implements IHangoutSummaryResponse {
    id?: string | undefined;
    title?: string | undefined;
    emoji?: string | undefined;
    location?: string | undefined;
    startTime?: Date;
    endTime?: Date | undefined;
    attendeeCount?: number;
    status?: HangoutStatus;
    currentUserRsvpStatus?: RSVPStatus;
    attendeeAvatarUrls?: string[] | undefined;

    constructor(data?: IHangoutSummaryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.title = _data["title"];
            this.emoji = _data["emoji"];
            this.location = _data["location"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
            this.attendeeCount = _data["attendeeCount"];
            this.status = _data["status"];
            this.currentUserRsvpStatus = _data["currentUserRsvpStatus"];
            if (Array.isArray(_data["attendeeAvatarUrls"])) {
                this.attendeeAvatarUrls = [] as any;
                for (let item of _data["attendeeAvatarUrls"])
                    this.attendeeAvatarUrls!.push(item);
            }
        }
    }

    static fromJS(data: any): HangoutSummaryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new HangoutSummaryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["title"] = this.title;
        data["emoji"] = this.emoji;
        data["location"] = this.location;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        data["attendeeCount"] = this.attendeeCount;
        data["status"] = this.status;
        data["currentUserRsvpStatus"] = this.currentUserRsvpStatus;
        if (Array.isArray(this.attendeeAvatarUrls)) {
            data["attendeeAvatarUrls"] = [];
            for (let item of this.attendeeAvatarUrls)
                data["attendeeAvatarUrls"].push(item);
        }
        return data;
    }
}

export interface IHangoutSummaryResponse {
    id?: string | undefined;
    title?: string | undefined;
    emoji?: string | undefined;
    location?: string | undefined;
    startTime?: Date;
    endTime?: Date | undefined;
    attendeeCount?: number;
    status?: HangoutStatus;
    currentUserRsvpStatus?: RSVPStatus;
    attendeeAvatarUrls?: string[] | undefined;
}

export enum RSVPStatus {
    Pending = "Pending",
    Going = "Going",
    NotGoing = "NotGoing",
    Maybe = "Maybe",
}

export class UpdateGroupRequest implements IUpdateGroupRequest {
    name?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;

    constructor(data?: IUpdateGroupRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.emoji = _data["emoji"];
            this.description = _data["description"];
        }
    }

    static fromJS(data: any): UpdateGroupRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateGroupRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["emoji"] = this.emoji;
        data["description"] = this.description;
        return data;
    }
}

export interface IUpdateGroupRequest {
    name?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
}

export class UpdateHangoutRequest implements IUpdateHangoutRequest {
    title?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    startTime?: Date | undefined;
    endTime?: Date | undefined;

    constructor(data?: IUpdateHangoutRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.title = _data["title"];
            this.emoji = _data["emoji"];
            this.description = _data["description"];
            this.location = _data["location"];
            this.startTime = _data["startTime"] ? new Date(_data["startTime"].toString()) : <any>undefined;
            this.endTime = _data["endTime"] ? new Date(_data["endTime"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): UpdateHangoutRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateHangoutRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["title"] = this.title;
        data["emoji"] = this.emoji;
        data["description"] = this.description;
        data["location"] = this.location;
        data["startTime"] = this.startTime ? this.startTime.toISOString() : <any>undefined;
        data["endTime"] = this.endTime ? this.endTime.toISOString() : <any>undefined;
        return data;
    }
}

export interface IUpdateHangoutRequest {
    title?: string | undefined;
    emoji?: string | undefined;
    description?: string | undefined;
    location?: string | undefined;
    startTime?: Date | undefined;
    endTime?: Date | undefined;
}

export class UpdateRSVPRequest implements IUpdateRSVPRequest {
    status?: RSVPStatus;

    constructor(data?: IUpdateRSVPRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.status = _data["status"];
        }
    }

    static fromJS(data: any): UpdateRSVPRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateRSVPRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["status"] = this.status;
        return data;
    }
}

export interface IUpdateRSVPRequest {
    status?: RSVPStatus;
}

export class UpdateUserRequest implements IUpdateUserRequest {
    firstName?: string | undefined;
    lastName?: string | undefined;
    profileImageUrl?: string | undefined;

    constructor(data?: IUpdateUserRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.profileImageUrl = _data["profileImageUrl"];
        }
    }

    static fromJS(data: any): UpdateUserRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateUserRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["profileImageUrl"] = this.profileImageUrl;
        return data;
    }
}

export interface IUpdateUserRequest {
    firstName?: string | undefined;
    lastName?: string | undefined;
    profileImageUrl?: string | undefined;
}

export class UserResponse implements IUserResponse {
    id?: string | undefined;
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    profileImageUrl?: string | undefined;
    createdAt?: Date;

    constructor(data?: IUserResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.email = _data["email"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.profileImageUrl = _data["profileImageUrl"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): UserResponse {
        data = typeof data === 'object' ? data : {};
        let result = new UserResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["email"] = this.email;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["profileImageUrl"] = this.profileImageUrl;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : <any>undefined;
        return data;
    }
}

export interface IUserResponse {
    id?: string | undefined;
    email?: string | undefined;
    firstName?: string | undefined;
    lastName?: string | undefined;
    profileImageUrl?: string | undefined;
    createdAt?: Date;
}

export class ApiException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}